# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='release_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
